service: takehome

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/takehome"

functions:
  getUser:
    handler: users/get.getUser
    events:
      - http: POST users/me
        cors: true
  signup:
    handler: users/signup.signup
    events:
      - http: POST users/signup
        cors: true
  updateWallet:
    handler: users/wallet.updateWallet
    events:
      - http: POST users/updateWallet
        cors: true
  getProducts:
    handler: products/get.getProducts
    events:
      - http: GET products/{distributor}
        request:
          parameters:
            paths:
              distributor: true
  myProducts:
    handler: products/mine.myProducts
    events:
      - http: POST products/mine
  createProduct:
    handler: products/create.createProduct
    events:
      - http: POST products/{distributor}
        request:
          parameters:
            paths:
              distributor: true
  updateProduct:
    handler: products/update.updateProduct
    events:
      - http: POST products/{distributor}/{id}/update
        request:
          parameters:
            paths:
              distributor: true
              id: true
  buyProduct:
    handler: products/buy.buyProduct
    events:
      - http: POST products/{distributor}/{id}/buy
        request:
          parameters:
            paths:
              distributor: true
              id: true
  reviewProduct:
    handler: products/review.reviewProduct
    events:
      - http: POST products/{distributor}/{id}/review
        request:
          parameters:
            paths:
              distributor: true
              id: true

package:
  exclude:
    - node_modules/**
    - .dynamodb/**

resources: # CloudFormation template syntax
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: takehome
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: username
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

# https://github.com/99xt/serverless-dynamodb-local
custom:
  dynamodb:
    stages:
      - dev
    start:
      migrate: true # Create template table on startup
      seed: unitTestingTemplate # Insert seed values into table on startup

    seed:
      unitTestingTemplate:
        sources:
          - table: takehome
            sources: [./seeds.json]

plugins:
  - serverless-dynamodb-local
